//
//  SWOTAnalysis.swift
//  Abimo
//

import Foundation

// MARK: - SWOTItem

struct SWOTItem: Identifiable, Codable, Hashable {
    var id: UUID
    let point: String
    let detail: String?       // rich 3–5 sentence explanation
    let score: Int            // 0–100
    let category: String

    enum CodingKeys: String, CodingKey {
        case id, point, detail, score, category
    }

    // Convenience init for legacy rows (no detail)
    init(point: String, score: Int, category: String) {
        self.id = UUID()
        self.point = point
        self.detail = nil
        self.score = score
        self.category = category
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        // id is generated by AI responses; preserved in JSONB for new analyses
        self.id = (try? container.decode(UUID.self, forKey: .id)) ?? UUID()
        self.point = try container.decode(String.self, forKey: .point)
        self.detail = try? container.decode(String.self, forKey: .detail)
        self.score = try container.decode(Int.self, forKey: .score)
        self.category = try container.decode(String.self, forKey: .category)
    }
}

// MARK: - MarketInsights

/// A real small business found by live web research — proof the dish sells
/// at a small table. Nested inside the market_insights jsonb.
struct MarketComparable: Codable, Hashable, Identifiable {
    var id: String { name }
    let name: String
    let what: String
    let pricing: String
    let status: String
    let url: String?
}

struct MarketInsights: Codable {
    let marketSize: String?
    let growthRate: String?
    let trendDirection: String?   // "up" | "down" | "stable"
    let keyCompetitors: [String]?
    let comparables: [MarketComparable]?

    enum CodingKeys: String, CodingKey {
        case marketSize      = "market_size"
        case growthRate      = "growth_rate"
        case trendDirection  = "trend_direction"
        case keyCompetitors  = "key_competitors"
        case comparables
    }
}

// MARK: - DimensionScores

/// The five 0-10 sub-scores behind the viability score. Keys stay camelCase
/// in the jsonb column — they mirror the edge-function response verbatim.
struct DimensionScores: Codable, Hashable {
    let problemSeverity: Int
    let demandEvidence: Int
    let marketQuality: Int
    let feasibility: Int
    let differentiation: Int
}

// MARK: - IdeaVariant

/// A "Remix the Recipe" variation: same core idea, one axis changed.
struct IdeaVariant: Codable, Hashable, Identifiable {
    var id: String { title }
    let title: String
    let pitch: String
    let differentiator: String
}

// MARK: - SWOTAnalysis

struct SWOTAnalysis: Identifiable, Codable {
    let id: UUID
    let transcriptionId: UUID

    // Legacy arrays — kept for backward compatibility with old DB rows
    let strengths: [String]
    let weaknesses: [String]
    let opportunities: [String]
    let threats: [String]

    let summary: String?
    let createdAt: Date

    // Rich fields added by migration (nullable — old rows have NULL)
    let strengthItems: [SWOTItem]?
    let weaknessItems: [SWOTItem]?
    let opportunityItems: [SWOTItem]?
    let threatItems: [SWOTItem]?
    let viabilityScore: Int?
    let marketContext: String?
    let marketInsights: MarketInsights?

    // Score transparency + remixes (nullable — rows before the overhaul have NULL)
    let dimensionScores: DimensionScores?
    let scoreRationale: String?
    let fatalFlaw: Bool?
    let ideaVariants: [IdeaVariant]?

    enum CodingKeys: String, CodingKey {
        case id
        case transcriptionId  = "transcription_id"
        case strengths
        case weaknesses
        case opportunities
        case threats
        case summary
        case createdAt        = "created_at"
        case strengthItems    = "strength_items"
        case weaknessItems    = "weakness_items"
        case opportunityItems = "opportunity_items"
        case threatItems      = "threat_items"
        case viabilityScore   = "viability_score"
        case marketContext    = "market_context"
        case marketInsights   = "market_insights"
        case dimensionScores  = "dimension_scores"
        case scoreRationale   = "score_rationale"
        case fatalFlaw        = "fatal_flaw"
        case ideaVariants     = "idea_variants"
    }

    // MARK: - Computed helpers (Charts fall back to score=50 for legacy rows)

    var resolvedStrengths: [SWOTItem] {
        strengthItems ?? strengths.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedWeaknesses: [SWOTItem] {
        weaknessItems ?? weaknesses.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedOpportunities: [SWOTItem] {
        opportunityItems ?? opportunities.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedThreats: [SWOTItem] {
        threatItems ?? threats.map { SWOTItem(point: $0, score: 50, category: "General") }
    }

    var avgStrengthScore: Double {
        let items = resolvedStrengths
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgWeaknessScore: Double {
        let items = resolvedWeaknesses
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgOpportunityScore: Double {
        let items = resolvedOpportunities
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgThreatScore: Double {
        let items = resolvedThreats
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
}
