//
//  SWOTAnalysis.swift
//  Abimo
//

import Foundation

// MARK: - SWOTItem

struct SWOTItem: Identifiable, Codable, Hashable {
    var id: UUID
    let point: String
    let detail: String?       // rich 3–5 sentence explanation
    let score: Int            // 0–100
    let category: String

    enum CodingKeys: String, CodingKey {
        case id, point, detail, score, category
    }

    // Convenience init for legacy rows (no detail)
    init(point: String, score: Int, category: String) {
        self.id = UUID()
        self.point = point
        self.detail = nil
        self.score = score
        self.category = category
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        // id is generated by AI responses; preserved in JSONB for new analyses
        self.id = (try? container.decode(UUID.self, forKey: .id)) ?? UUID()
        self.point = try container.decode(String.self, forKey: .point)
        self.detail = try? container.decode(String.self, forKey: .detail)
        self.score = try container.decode(Int.self, forKey: .score)
        self.category = try container.decode(String.self, forKey: .category)
    }
}

// MARK: - MarketInsights

/// A real small business found by live web research — proof the dish sells
/// at a small table. Nested inside the market_insights jsonb.
struct MarketComparable: Codable, Hashable, Identifiable {
    var id: String { name }
    let name: String
    let what: String
    let pricing: String
    let status: String
    let url: String?
    // Idea-aware comparison, added at analysis time (nil on older rows)
    let overlap: String?   // what it shares with the founder's idea
    let edge: String?      // how the founder's idea differs / could win
    // Scoring v2 numbers from research-market (nil on the analyze-swot copy
    // and on older digests)
    var priceAmount: Double? = nil
    var priceCurrency: String? = nil
    var pricePeriod: String? = nil      // month | year | one_time | free | unknown
    var chargesMoney: String? = nil     // yes | no | unknown
    var size: String? = nil             // solo | small_team | company | giant | unknown
    var userCountHint: Double? = nil
    var userCountSource: String? = nil
    var lastActive: String? = nil       // 2025_or_later | 2023_2024 | older | unknown

    enum CodingKeys: String, CodingKey {
        case name, what, pricing, status, url, overlap, edge
        case priceAmount     = "price_amount"
        case priceCurrency   = "price_currency"
        case pricePeriod     = "price_period"
        case chargesMoney    = "charges_money"
        case size
        case userCountHint   = "user_count_hint"
        case userCountSource = "user_count_source"
        case lastActive      = "last_active"
    }

    init(name: String, what: String, pricing: String, status: String,
         url: String?, overlap: String? = nil, edge: String? = nil) {
        self.name = name
        self.what = what
        self.pricing = pricing
        self.status = status
        self.url = url
        self.overlap = overlap
        self.edge = edge
    }
}

// MARK: - ResearchDigest

/// One demand signal the scout found, with direction and weight.
struct ResearchSignal: Codable, Hashable, Identifiable {
    var id: String { text }
    let text: String
    let url: String?
    let sourceType: String?   // reddit | forum | review | app_store | news | blog | social | marketplace | other
    let direction: String?    // positive | negative
    let strength: String?     // weak | moderate | strong
    let recency: String?
    let countHint: Double?

    enum CodingKeys: String, CodingKey {
        case text, url, direction, strength, recency
        case sourceType = "source_type"
        case countHint  = "count_hint"
    }
}

/// The numbers block of a v2 research digest — what the scorer's evidence
/// caps read.
struct ResearchMarket: Codable, Hashable {
    let paidComparablesFound: Int?
    let freeAlternativesDominate: String?
    let saturation: String?
    let smallPlayersMakingMoney: String?
    let giantBlocksNiche: String?
    let giantName: String?
    let typicalPriceLow: Double?
    let typicalPriceHigh: Double?
    let priceCurrency: String?
    let searchQuality: String?
    let queriesRun: [String]?

    enum CodingKeys: String, CodingKey {
        case paidComparablesFound     = "paid_comparables_found"
        case freeAlternativesDominate = "free_alternatives_dominate"
        case saturation
        case smallPlayersMakingMoney  = "small_players_making_money"
        case giantBlocksNiche         = "giant_blocks_niche"
        case giantName                = "giant_name"
        case typicalPriceLow          = "typical_price_low"
        case typicalPriceHigh         = "typical_price_high"
        case priceCurrency            = "price_currency"
        case searchQuality            = "search_quality"
        case queriesRun               = "queries_run"
    }
}

/// Live web research digest from the research-market edge function. The
/// first three fields are the legacy prose digest; `signals` and `market`
/// arrived with scoring v2 and are nil on older digests.
struct ResearchDigest: Codable {
    let comparables: [MarketComparable]
    let nicheNotes: String
    let demandSignals: [String]
    var signals: [ResearchSignal]? = nil
    var market: ResearchMarket? = nil

    enum CodingKeys: String, CodingKey {
        case comparables, signals, market
        case nicheNotes    = "niche_notes"
        case demandSignals = "demand_signals"
    }

    var isEmpty: Bool {
        comparables.isEmpty && nicheNotes.isEmpty && demandSignals.isEmpty && (signals ?? []).isEmpty
    }
}

struct MarketInsights: Codable {
    let marketSize: String?
    let growthRate: String?
    let trendDirection: String?   // "up" | "down" | "stable"
    let keyCompetitors: [String]?
    let comparables: [MarketComparable]?

    enum CodingKeys: String, CodingKey {
        case marketSize      = "market_size"
        case growthRate      = "growth_rate"
        case trendDirection  = "trend_direction"
        case keyCompetitors  = "key_competitors"
        case comparables
    }
}

// MARK: - DimensionScores

/// The five 0-10 sub-scores behind the viability score. Keys stay camelCase
/// in the jsonb column — they mirror the edge-function response verbatim.
struct DimensionScores: Codable, Hashable {
    let problemSeverity: Int
    let demandEvidence: Int
    let marketQuality: Int
    let feasibility: Int
    let differentiation: Int

    func value(for key: DimensionKey) -> Int {
        switch key {
        case .problemSeverity: return problemSeverity
        case .demandEvidence:  return demandEvidence
        case .marketQuality:   return marketQuality
        case .feasibility:     return feasibility
        case .differentiation: return differentiation
        }
    }
}

/// The five dimensions, keyed exactly as the edge function names them.
enum DimensionKey: String, CaseIterable, Identifiable {
    case problemSeverity, demandEvidence, marketQuality, feasibility, differentiation
    var id: String { rawValue }

    var label: String {
        switch self {
        case .problemSeverity: return "Problem"
        case .demandEvidence:  return "Demand"
        case .marketQuality:   return "Market"
        case .feasibility:     return "Buildable"
        case .differentiation: return "Different"
        }
    }
}

/// The model's one evidence sentence per dimension (scoring v2).
struct DimensionEvidence: Codable, Hashable {
    let problemSeverity: String?
    let demandEvidence: String?
    let marketQuality: String?
    let feasibility: String?
    let differentiation: String?

    func text(for key: DimensionKey) -> String? {
        switch key {
        case .problemSeverity: return problemSeverity
        case .demandEvidence:  return demandEvidence
        case .marketQuality:   return marketQuality
        case .feasibility:     return feasibility
        case .differentiation: return differentiation
        }
    }
}

/// Concrete numbers the founder stated about demand, extracted before judging.
struct FounderEvidence: Codable, Hashable {
    let citesConcreteNumbers: Bool
    let quotes: [String]
    let strongest: String   // none | anecdote | personal_experience | community_size | poll | waitlist | prepayments | revenue
}

// MARK: - ScoreMeta (scoring v2 receipt)

struct ScoreCap: Codable, Hashable {
    let dim: String
    let from: Int
    let to: Int
    let reason: String
}

struct ScoreAdjustment: Codable, Hashable {
    let kind: String     // hedged | founder_numbers | dead_dimension | fatal_flaw | ceiling
    let delta: Int?
    let cap: Int?
    let reason: String
}

/// Everything the server did to turn five dimensions into the number —
/// weights, caps, gate, map, adjustments. Mirrors _shared/scoring.ts.
struct ScoreMeta: Codable, Hashable {
    let version: Int
    let weights: [String: Double]?
    let rawDims: DimensionScores?
    let cappedDims: DimensionScores?
    let wm: Double?
    let gate: Double?
    let demandFactor: Double?
    let raw: Double?
    let mapped: Double?
    let caps: [ScoreCap]?
    let adjustments: [ScoreAdjustment]?
    let hedged: Bool?
    let verdictBand: String?
    let computedBand: String?
    let bandMismatch: Bool?
    let evidenceStrength: String?

    func cap(for key: DimensionKey) -> ScoreCap? {
        caps?.first { $0.dim == key.rawValue }
    }

    func weight(for key: DimensionKey) -> Double? {
        weights?[key.rawValue]
    }
}

// MARK: - IdeaVariant

/// A "Remix the Recipe" variation: same core idea, one axis changed.
struct IdeaVariant: Codable, Hashable, Identifiable {
    var id: String { title }
    let title: String
    let pitch: String
    let differentiator: String
    // vs-the-original comparison (nil on rows from before the polish round)
    let keeps: String?     // what stays from the original idea
    let changes: String?   // what's different or added

    init(title: String, pitch: String, differentiator: String,
         keeps: String? = nil, changes: String? = nil) {
        self.title = title
        self.pitch = pitch
        self.differentiator = differentiator
        self.keeps = keeps
        self.changes = changes
    }
}

// MARK: - SWOTAnalysis

struct SWOTAnalysis: Identifiable, Codable {
    let id: UUID
    let transcriptionId: UUID

    // Legacy arrays — kept for backward compatibility with old DB rows
    let strengths: [String]
    let weaknesses: [String]
    let opportunities: [String]
    let threats: [String]

    let summary: String?
    let createdAt: Date

    // Rich fields added by migration (nullable — old rows have NULL)
    let strengthItems: [SWOTItem]?
    let weaknessItems: [SWOTItem]?
    let opportunityItems: [SWOTItem]?
    let threatItems: [SWOTItem]?
    let viabilityScore: Int?
    let marketContext: String?
    let marketInsights: MarketInsights?

    // Score transparency + remixes (nullable — rows before the overhaul have NULL)
    let dimensionScores: DimensionScores?
    let scoreRationale: String?
    let fatalFlaw: Bool?
    let ideaVariants: [IdeaVariant]?

    // Scoring v2 receipt (nil on rows scored with the old recipe). Defaults
    // keep the memberwise init source-compatible with older call sites.
    var scoringVersion: Int? = nil
    var verdictBand: String? = nil
    var verdictReason: String? = nil
    var dimensionEvidence: DimensionEvidence? = nil
    var scoreMeta: ScoreMeta? = nil
    var evidenceStrength: String? = nil      // none | thin | ok | rich
    var fatalFlawReason: String? = nil
    var researchDigest: ResearchDigest? = nil
    var scoreAuditId: UUID? = nil

    /// Rows scored before v2 show a footnote and no weights/caps UI.
    var isLegacyScoring: Bool { (scoringVersion ?? 1) < 2 }

    enum CodingKeys: String, CodingKey {
        case id
        case transcriptionId  = "transcription_id"
        case strengths
        case weaknesses
        case opportunities
        case threats
        case summary
        case createdAt        = "created_at"
        case strengthItems    = "strength_items"
        case weaknessItems    = "weakness_items"
        case opportunityItems = "opportunity_items"
        case threatItems      = "threat_items"
        case viabilityScore   = "viability_score"
        case marketContext    = "market_context"
        case marketInsights   = "market_insights"
        case dimensionScores  = "dimension_scores"
        case scoreRationale   = "score_rationale"
        case fatalFlaw        = "fatal_flaw"
        case ideaVariants     = "idea_variants"
        case scoringVersion    = "scoring_version"
        case verdictBand       = "verdict_band"
        case verdictReason     = "verdict_reason"
        case dimensionEvidence = "dimension_evidence"
        case scoreMeta         = "score_meta"
        case evidenceStrength  = "evidence_strength"
        case fatalFlawReason   = "fatal_flaw_reason"
        case researchDigest    = "research_digest"
        case scoreAuditId      = "score_audit_id"
    }

    // MARK: - Computed helpers (Charts fall back to score=50 for legacy rows)

    var resolvedStrengths: [SWOTItem] {
        strengthItems ?? strengths.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedWeaknesses: [SWOTItem] {
        weaknessItems ?? weaknesses.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedOpportunities: [SWOTItem] {
        opportunityItems ?? opportunities.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedThreats: [SWOTItem] {
        threatItems ?? threats.map { SWOTItem(point: $0, score: 50, category: "General") }
    }

    var avgStrengthScore: Double {
        let items = resolvedStrengths
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgWeaknessScore: Double {
        let items = resolvedWeaknesses
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgOpportunityScore: Double {
        let items = resolvedOpportunities
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgThreatScore: Double {
        let items = resolvedThreats
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
}
